#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

clone_depth: 3

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release
  
environment:
  matrix:
    - TOOLSET: v140
  
matrix:
  fast_finish: true

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - git submodule update --init --recursive

before_build:
  - if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmake . -G "%CMAKE_GENERATOR_NAME%" -T %TOOLSET% -DCMAKE_BUILD_TYPE=%configuration% -Bbuild

build:
  project: build/CPP_BOILERPLATE.sln
  parallel: true
  verbosity: minimal
  
test_script:
  - cmake --build build --target test

