name: CI

on:
  push:
  pull_request:

jobs:
  build-ubuntu:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
          submodules: true

    - name: Configure (Debug)
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=debug ..

    - name: Build with ${{ matrix.compiler }}
      run: cmake --build build

    - name: Test (Unix)
      if: startsWith(runner.os, 'Windows') == false
      run: cd build && ctest

    - name: Test (Windows)
      if: startsWith(runner.os, 'Windows')
      run: |
        cd build
        set CTEST_OUTPUT_ON_FAILURE=1
        ctest -C Debug
