name: CI

on:
  push:
  pull_request:

jobs:
  build-ubuntu:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc

        configuration:
          - Debug
          # TODO: To be enabled in the future
          # - Release

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
          submodules: true

    - name: Configure (${{ matrix.configuration }})
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} ..

    - name: Build with ${{ matrix.compiler }}
      run: cmake --build build

    - name: Test
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: |
        cd build
        ctest -C ${{ matrix.configuration }}
